import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy | Codirity",
  description:
    "Learn how Codirity collects, uses, and protects your personal information.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      {/* Hero Section */}
      <section className="pt-32 pb-16 md:pt-40 md:pb-20 px-4 md:px-8">
        <div className="max-w-4xl mx-auto">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-brand transition-colors duration-300 mb-8"
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="text-sm font-medium">Back to Home</span>
          </Link>

          <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 dark:text-white tracking-tight mb-6">
            Privacy Policy
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-400">
            Effective date: December 17, 2024
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="pb-20 md:pb-28 px-4 md:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="space-y-12 text-gray-600 dark:text-gray-400">
            {/* Section 1 - Introduction */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                1. Introduction
              </h2>
              <div className="space-y-4">
                <p>
                  Welcome to <strong className="text-gray-900 dark:text-white">Codirity</strong>.
                </p>
                <p>
                  Codirity (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates https://codirity.com (hereinafter referred to as &quot;<strong className="text-gray-900 dark:text-white">Service</strong>&quot;).
                </p>
                <p>
                  Our Privacy Policy governs your visit to https://codirity.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.
                </p>
                <p>
                  We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
                </p>
                <p>
                  Our Terms and Conditions (&quot;<strong className="text-gray-900 dark:text-white">Terms</strong>&quot;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&quot;<strong className="text-gray-900 dark:text-white">agreement</strong>&quot;).
                </p>
              </div>
            </div>

            {/* Section 2 - Definitions */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                2. Definitions
              </h2>
              <div className="space-y-4">
                <p>
                  <strong className="text-gray-900 dark:text-white">SERVICE</strong> means the https://codirity.com website operated by Codirity.
                </p>
                <p>
                  <strong className="text-gray-900 dark:text-white">PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                </p>
                <p>
                  <strong className="text-gray-900 dark:text-white">USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).
                </p>
                <p>
                  <strong className="text-gray-900 dark:text-white">COOKIES</strong> are small files stored on your device (computer or mobile device).
                </p>
                <p>
                  <strong className="text-gray-900 dark:text-white">DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
                </p>
                <div className="bg-gray-50 dark:bg-gray-800 rounded-2xl p-6 space-y-4">
                  <p>
                    <strong className="text-gray-900 dark:text-white">DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                  </p>
                  <p>
                    <strong className="text-gray-900 dark:text-white">DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.
                  </p>
                  <p>
                    <strong className="text-gray-900 dark:text-white">THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
                  </p>
                </div>
              </div>
            </div>

            {/* Section 3 - Information Collection and Use */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                3. Information Collection and Use
              </h2>
              <p>
                We collect several different types of information for various purposes to provide and improve our Service to you.
              </p>
            </div>

            {/* Section 4 - Types of Data Collected */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                4. Types of Data Collected
              </h2>
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                    Personal Data
                  </h3>
                  <p className="mb-4">
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;<strong className="text-gray-900 dark:text-white">Personal Data</strong>&quot;). Personally identifiable information may include, but is not limited to:
                  </p>
                  <ol className="list-decimal pl-6 space-y-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Company name</li>
                    <li>Cookies and Usage Data</li>
                  </ol>
                  <p className="mt-4">
                    We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                    Usage Data
                  </h3>
                  <p className="mb-4">
                    We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (&quot;<strong className="text-gray-900 dark:text-white">Usage Data</strong>&quot;).
                  </p>
                  <p className="mb-4">
                    This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                  <p>
                    When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                  </p>
                </div>

                <div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                    Tracking Cookies Data
                  </h3>
                  <p className="mb-4">
                    We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
                  </p>
                  <p className="mb-4">
                    Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
                  </p>
                  <p className="mb-4">
                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                  </p>
                  <p className="mb-3">Examples of Cookies we use:</p>
                  <ol className="list-decimal pl-6 space-y-2">
                    <li><strong className="text-gray-900 dark:text-white">Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
                    <li><strong className="text-gray-900 dark:text-white">Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
                    <li><strong className="text-gray-900 dark:text-white">Security Cookies:</strong> We use Security Cookies for security purposes.</li>
                    <li><strong className="text-gray-900 dark:text-white">Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
                  </ol>
                </div>
              </div>
            </div>

            {/* Section 5 - Use of Data */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                5. Use of Data
              </h2>
              <p className="mb-4">Codirity uses the collected data for various purposes:</p>
              <ol className="list-decimal pl-6 space-y-2">
                <li>to provide and maintain our Service;</li>
                <li>to notify you about changes to our Service;</li>
                <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
                <li>to provide customer support;</li>
                <li>to gather analysis or valuable information so that we can improve our Service;</li>
                <li>to monitor the usage of our Service;</li>
                <li>to detect, prevent and address technical issues;</li>
                <li>to fulfill any other purpose for which you provide it;</li>
                <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
                <li>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
                <li>in any other way we may describe when you provide the information;</li>
                <li>for any other purpose with your consent.</li>
              </ol>
            </div>

            {/* Section 6 - Retention of Data */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                6. Retention of Data
              </h2>
              <div className="space-y-4">
                <p>
                  We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p>
                  We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                </p>
              </div>
            </div>

            {/* Section 7 - Transfer of Data */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                7. Transfer of Data
              </h2>
              <div className="space-y-4">
                <p>
                  Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
                </p>
                <p>
                  If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
                </p>
                <p>
                  Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                </p>
                <p>
                  Codirity will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>
              </div>
            </div>

            {/* Section 8 - Disclosure of Data */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                8. Disclosure of Data
              </h2>
              <p className="mb-4">We may disclose personal information that we collect, or you provide:</p>
              <div className="space-y-6">
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    Disclosure for Law Enforcement
                  </h3>
                  <p>
                    Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.
                  </p>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    Business Transaction
                  </h3>
                  <p>
                    If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.
                  </p>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-2">
                    Other cases. We may disclose your information also:
                  </h3>
                  <ol className="list-decimal pl-6 space-y-2 mt-2">
                    <li>to our subsidiaries and affiliates;</li>
                    <li>to contractors, service providers, and other third parties we use to support our business;</li>
                    <li>to fulfill the purpose for which you provide it;</li>
                    <li>for the purpose of including your company&apos;s logo on our website;</li>
                    <li>for any other purpose disclosed by us when you provide the information;</li>
                    <li>with your consent in any other cases.</li>
                  </ol>
                </div>
              </div>
            </div>

            {/* Section 9 - Security of Data */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                9. Security of Data
              </h2>
              <p>
                The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
              </p>
            </div>

            {/* Section 10 - Service Providers */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                10. Service Providers
              </h2>
              <p>
                We may employ third party companies and individuals to facilitate our Service (&quot;<strong className="text-gray-900 dark:text-white">Service Providers</strong>&quot;), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.
              </p>
              <p className="mt-4">
                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
              </p>
            </div>

            {/* Section 11 - Analytics */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                11. Analytics
              </h2>
              <p className="mb-4">
                We may use third-party Service Providers to monitor and analyze the use of our Service.
              </p>
              <div className="bg-gray-50 dark:bg-gray-800 rounded-2xl p-6 space-y-4">
                <p className="font-semibold text-gray-900 dark:text-white">Google Analytics</p>
                <p>
                  Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.
                </p>
                <p>
                  For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: https://policies.google.com/privacy?hl=en
                </p>
                <p>
                  We also encourage you to review Google&apos;s policy for safeguarding your data: https://support.google.com/analytics/answer/6004245.
                </p>
              </div>
            </div>

            {/* Section 12 - Links to Other Sites */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                12. Links to Other Sites
              </h2>
              <p className="mb-4">
                Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.
              </p>
              <div className="bg-gray-50 dark:bg-gray-800 rounded-2xl p-6">
                <p>
                  We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                </p>
              </div>
            </div>

            {/* Section 13 - Children's Privacy */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                13. Children&apos;s Privacy
              </h2>
              <div className="bg-gray-50 dark:bg-gray-800 rounded-2xl p-6 space-y-4">
                <p>
                  Our Services are not intended for use by children under the age of 13 (&quot;Children&quot;).
                </p>
                <p>
                  We do not knowingly collect personally identifiable information from Children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.
                </p>
              </div>
            </div>

            {/* Section 14 - Changes to This Privacy Policy */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                14. Changes to This Privacy Policy
              </h2>
              <div className="space-y-4">
                <p>
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                </p>
                <p>
                  We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update &quot;effective date&quot; at the top of this Privacy Policy.
                </p>
                <p>
                  You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>
              </div>
            </div>

            {/* Section 15 - Contact Us */}
            <div>
              <h2 className="text-2xl md:text-3xl font-bold text-gray-900 dark:text-white mb-4">
                15. Contact Us
              </h2>
              <p className="mb-4">
                If you have any questions about this Privacy Policy, please contact us:
              </p>
              <div className="bg-gray-50 dark:bg-gray-800 rounded-2xl p-6">
                <p>
                  By email: <a href="mailto:support@codirity.com" className="text-brand hover:underline">support@codirity.com</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
